#!/bin/bash
# =============================================================================
# Register a private payload repository with this vehicle.
#
#   ./scripts/register-payload.sh <payload-name> <org>
#
# Generates a dedicated SSH deploy key, adds a matching host alias to
# ~/.ssh/config, and appends an entry to deployment/payload-registry.yaml.
#
# One key per payload is deliberate. A deploy key on GitHub grants access to a
# single repository, so a vehicle that is lost or compromised exposes only the
# payloads actually installed on it — not the whole organisation. The host
# alias is what lets several single-repository keys coexist: git resolves
# `git@github-<name>:org/repo.git` through the alias and picks the right key.
#
# Payloads in public repositories need none of this — put the https:// URL
# straight into deployment/payload-registry.yaml.
# =============================================================================
set -euo pipefail

if [[ $# -lt 2 ]]; then
    echo "Usage: ./scripts/register-payload.sh <payload-name> <github-org>" >&2
    echo "Example: ./scripts/register-payload.sh hydrophone-payload BlueLab-ICM" >&2
    exit 1
fi

PAYLOAD_NAME="$1"
ORG_NAME="$2"
KEY_FILE="$HOME/.ssh/blueboat-${PAYLOAD_NAME}"
SSH_CONFIG="$HOME/.ssh/config"
BASE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
REGISTRY_FILE="$BASE_DIR/deployment/payload-registry.yaml"

echo "Registering payload: $PAYLOAD_NAME (org: $ORG_NAME)"

# --- 1. Deploy key ----------------------------------------------------------
if [[ -f "$KEY_FILE" ]]; then
    echo "Key already exists at $KEY_FILE — reusing it."
else
    echo "Generating an Ed25519 deploy key..."
    ssh-keygen -t ed25519 -f "$KEY_FILE" -C "deploy-key-$PAYLOAD_NAME" -N "" >/dev/null
fi

# --- 2. SSH host alias ------------------------------------------------------
mkdir -p "$(dirname "$SSH_CONFIG")"
touch "$SSH_CONFIG"
if grep -q "Host github-${PAYLOAD_NAME}\$" "$SSH_CONFIG"; then
    echo "SSH alias github-${PAYLOAD_NAME} already present."
else
    echo "Adding SSH alias github-${PAYLOAD_NAME}..."
    # IdentitiesOnly=yes stops the SSH agent from offering every other key
    # first; GitHub authenticates the first key it accepts, which would
    # otherwise be the wrong repository's.
    cat >>"$SSH_CONFIG" <<EOF

# --- generated by register-payload.sh: $PAYLOAD_NAME ---
Host github-${PAYLOAD_NAME}
    HostName github.com
    User git
    IdentityFile $KEY_FILE
    IdentitiesOnly yes
EOF
fi

# --- 3. Registry entry ------------------------------------------------------
if grep -q "name: ${PAYLOAD_NAME}\$" "$REGISTRY_FILE" 2>/dev/null; then
    echo "Payload already listed in $REGISTRY_FILE."
else
    echo "Appending to $REGISTRY_FILE..."
    # A file without a trailing newline would splice this entry onto the last
    # line of the previous one and produce invalid YAML.
    if [[ -s "$REGISTRY_FILE" && -n "$(tail -c1 "$REGISTRY_FILE")" ]]; then
        printf '\n' >>"$REGISTRY_FILE"
    fi
    cat >>"$REGISTRY_FILE" <<EOF
  - name: ${PAYLOAD_NAME}
    repo: git@github-${PAYLOAD_NAME}:${ORG_NAME}/${PAYLOAD_NAME}.git
    version: main
    enabled: true
EOF
fi

# --- 4. Manual step ---------------------------------------------------------
cat <<EOF

===================================================
Add this public key as a deploy key on the repository:
  https://github.com/${ORG_NAME}/${PAYLOAD_NAME}/settings/keys

--- copy below this line ---
$(cat "${KEY_FILE}.pub")
--- copy above this line ---

Read-only access is enough; leave "Allow write access" unchecked.
Then fetch and build the payload with:
  ./scripts/sync-payloads.sh
EOF
